version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    command:
      - bash
      - -lc
      - |
        /etc/confluent/docker/run &
        echo "Waiting for Kafka to be ready..."
        cub kafka-ready -b kafka:9092 1 30
        kafka-topics --create --if-not-exists --topic clickstream --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3
        wait

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  producer:
    image: python:3.11-slim
    depends_on:
      - kafka
    working_dir: /opt/app
    volumes:
      - ./app/producer:/opt/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TOPIC_NAME: clickstream
      RATE_PER_SEC: "5"
    command: bash -lc "pip install --no-cache-dir kafka-python faker && python producer.py"

  spark:
    image: bitnami/spark:3.5.1
    user: root
    depends_on:
      - kafka
      - postgres
    environment:
      - SPARK_MODE=driver
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYSPARK_PYTHON=python3
    volumes:
      - ./app:/opt/app
    command: >
      bash -lc "
      /opt/bitnami/spark/bin/spark-submit
        --master local[*]
        --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.postgresql:postgresql:42.7.3
        /opt/app/spark_streaming_job.py
      "
